name: "my hello action"

description: "Say hellow with GitHub actions"

inputs:
  first-greeting:
    description: "who would you like to greet in console"
    required: true
    default: "Hubot"
  
  second-greeting:
    description: "another person to greet"
    required: true
    default: "Mona the Octocat"

  third-greeting:
    description: "a third greeting"
    required: false

runs:
  using: "node12"
  main: "main.js"